import {
	ATLAS_FONT,
	DESKTOP,
	FIELD_ACCENT,
	FIELD_BAND_OUTER,
	FIELD_MAX,
	FIELD_MAX_EDGE,
	SCROLL_DAMP,
	SCROLL_SETTLE_MS,
	MOBILE,
	PRESETS,
	type FieldPreset,
} from "./ascii-config"

/* -------------------------------------------------------------------------- */
/* Pure functions — unit tested directly                                       */
/* -------------------------------------------------------------------------- */

/**
 * Ordered-dither threshold matrix, generated by recursive doubling:
 *
 *     M_2n = [ 4M      4M + 2 ]
 *            [ 4M + 3  4M + 1 ]
 *
 * Thresholds are taken at cell midpoints — `(i + 0.5) / n² - 0.5` — so the
 * matrix has a mean of exactly zero. Using `i / n²` instead leaves a half-step
 * bias that darkens the whole field as density changes.
 */
export function bayer(n: 2 | 4 | 8 | 16): Float32Array {
	let m: number[][] = [
		[0, 2],
		[3, 1],
	]
	while (m.length < n) {
		const s = m.length
		const next: number[][] = Array.from({ length: s * 2 }, () => new Array(s * 2).fill(0))
		for (let y = 0; y < s; y++) {
			for (let x = 0; x < s; x++) {
				const v = m[y][x] * 4
				next[y][x] = v
				next[y][x + s] = v + 2
				next[y + s][x] = v + 3
				next[y + s][x + s] = v + 1
			}
		}
		m = next
	}
	const out = new Float32Array(n * n)
	const d = n * n
	for (let y = 0; y < n; y++) {
		for (let x = 0; x < n; x++) out[y * n + x] = (m[y][x] + 0.5) / d - 0.5
	}
	return out
}

export const BAYER8 = bayer(8)

/**
 * Is this column outside the text column, and therefore allowed the bright
 * gutter tier?
 *
 * This is the whole accessibility contract of the two-tier field, so it is a
 * pure function rather than an inline expression buried in the draw loop: the
 * invariant "no cell inside the content band is ever painted brighter than
 * FIELD_MAX" is asserted against it directly.
 *
 * `bandHalfPx` is the mask's OUTER edge, not its inner one. Between the two the
 * mask is mid-fade, so a bright cell there would be partly visible behind
 * content that runs close to the shell edge.
 */
export function isGutterCell(
	x: number,
	cellW: number,
	viewportW: number,
	bandHalfPx: number = FIELD_BAND_OUTER
): boolean {
	const centre = viewportW / 2
	const cellLeft = x * cellW
	const cellRight = cellLeft + cellW
	// The whole cell must clear the band; a cell straddling the edge stays dim.
	return cellRight <= centre - bandHalfPx || cellLeft >= centre + bandHalfPx
}

/**
 * Three directional travelling waves. Deterministic, allocation-free, and at
 * 12–15fps behind a mask it reads as drifting cloud rather than noise. Simplex
 * noise would cost 2–3KB and ~10x the work for a difference nobody can see.
 *
 * Two properties are load-bearing and easy to break while "simplifying" this:
 *
 *  - Each wave travels along its own axis, and the spatial frequencies fit
 *    several periods into a viewport. Axis-aligned waves at low frequency
 *    (`sin(x*0.05)`, `sin(y*0.07)`) instead produce visible horizontal banding.
 *  - The frequencies are mutually non-commensurate, so the *mean* brightness of
 *    the visible window stays flat as t advances. Get this wrong and the whole
 *    page slowly pulses light and dark, which is both distracting and a contrast
 *    hazard. Measured mean swing here is ~0.005; the naive version was ~0.093.
 *
 * @returns a value in [0, 1]
 */
export function field(x: number, y: number, t: number): number {
	const a = Math.sin(x * 0.16 + y * 0.07 + t)
	const b = Math.sin(-x * 0.09 + y * 0.19 - t * 0.73)
	const c = Math.sin(x * 0.12 - y * 0.13 + t * 0.41)
	return (a + b + c) / 6 + 0.5
}

/**
 * Dither strength, as a fraction of one glyph step. Full strength (1.0) makes
 * the 8x8 Bayer tile's two-row structure read as scanlines; half strength keeps
 * the dither as texture.
 */
export const DITHER = 0.5

/**
 * Per-glyph alpha curve. Gamma-shaped so the ramp reads evenly, and scaled so
 * the brightest glyph lands exactly on `--field-max` — this is where the
 * contrast cap is enforced in code rather than by hoping.
 */
export function alphaRamp(len: number): Float32Array {
	const out = new Float32Array(len)
	for (let i = 0; i < len; i++) out[i] = (i / Math.max(1, len - 1)) ** 1.4
	return out
}

/* -------------------------------------------------------------------------- */
/* Engine                                                                      */
/* -------------------------------------------------------------------------- */

export interface EngineParams {
	current: FieldPreset
	target: FieldPreset
}

interface Grid {
	cols: number
	rows: number
	cw: number
	ch: number
}

function prefersReducedMotion(): boolean {
	return typeof matchMedia === "function" && matchMedia("(prefers-reduced-motion: reduce)").matches
}

/** Low-end devices get the static Bayer texture only — the loop never starts. */
function isLowPower(): boolean {
	const nav = navigator as Navigator & {
		deviceMemory?: number
		connection?: { saveData?: boolean }
	}
	if (nav.connection?.saveData) return true
	if (typeof nav.deviceMemory === "number" && nav.deviceMemory <= 4) return true
	if (typeof nav.hardwareConcurrency === "number" && nav.hardwareConcurrency <= 4) return true
	return false
}

/**
 * Glyphs are rasterised in `colour`, not white.
 *
 * This is where the contrast cap is actually enforced: the base atlas is drawn
 * in FIELD_MAX, so even at alpha 1.0 the brightest possible cell is exactly
 * `--field-max` and the AA contrast figure for body text holds without relying
 * on the CSS mask to dim it. Rasterising white and hoping the mask compensates
 * would put an untested CSS value in charge of an accessibility guarantee.
 */
function buildAtlas(
	ramp: string,
	cw: number,
	ch: number,
	dpr: number,
	colour: string
): HTMLCanvasElement {
	const atlas = document.createElement("canvas")
	atlas.width = Math.ceil(cw * dpr * ramp.length)
	atlas.height = Math.ceil(ch * dpr)
	const c = atlas.getContext("2d")!
	c.scale(dpr, dpr)
	c.font = `${Math.round(ch * 0.78)}px ${ATLAS_FONT}`
	c.textBaseline = "middle"
	c.textAlign = "center"
	c.fillStyle = colour
	for (let i = 0; i < ramp.length; i++) {
		c.fillText(ramp[i], i * cw + cw / 2, ch / 2)
	}
	return atlas
}

/**
 * Stable per-cell value in [0, 1). A cheap integer hash rather than something
 * like `(x * 7 + y * 13) & 63`, which lays the accent cells out on a visible
 * diagonal lattice instead of scattering them.
 */
export function hash01(x: number, y: number): number {
	let h = Math.imul(x, 374761393) + Math.imul(y, 668265263)
	h = Math.imul(h ^ (h >>> 13), 1274126177)
	return ((h ^ (h >>> 16)) >>> 0) / 4294967296
}

export function createEngine(
	canvas: HTMLCanvasElement,
	paramsRef: { current: EngineParams }
): { destroy: () => void } {
	const wrap = canvas.parentElement ?? canvas
	const coarse = typeof matchMedia === "function" && matchMedia("(pointer: coarse)").matches
	const tier = coarse || window.innerWidth < 768 ? MOBILE : DESKTOP
	const interval = 1000 / tier.fps

	const ctx = canvas.getContext("2d", { alpha: true })
	if (!ctx) return { destroy: () => {} }

	let dpr = 1
	let grid: Grid = { cols: 0, rows: 0, cw: tier.cellW, ch: tier.cellH }
	let prev = new Uint8Array(0)
	let atlas: HTMLCanvasElement | null = null
	let atlasEdge: HTMLCanvasElement | null = null
	let atlasAccent: HTMLCanvasElement | null = null
	let atlasRamp = ""
	let cssWidth = 0
	let alpha = alphaRamp(1)
	let raf = 0
	let last = 0
	let clock = 0
	let damp = 1
	let dampTarget = 1
	let scrollTimer: ReturnType<typeof setTimeout> | undefined
	let reduced = prefersReducedMotion()
	let destroyed = false

	function layout() {
		const cssW = wrap.clientWidth || window.innerWidth
		const cssH = wrap.clientHeight || window.innerHeight
		dpr = Math.min(window.devicePixelRatio || 1, tier.dprCap)

		// Grow the cell rather than the grid so an ultrawide costs the same as a
		// laptop. The cell clamp, not the fps gate, is the real safety net.
		let cw: number = tier.cellW
		let ch: number = tier.cellH
		while (Math.ceil(cssW / cw) * Math.ceil(cssH / ch) > tier.maxCells) {
			cw += 1
			ch = Math.round(cw * (tier.cellH / tier.cellW))
		}

		const cols = Math.ceil(cssW / cw)
		const rows = Math.ceil(cssH / ch)

		// Both the backing store and the CSS box are set explicitly, so the canvas
		// never contributes layout shift.
		canvas.width = Math.round(cssW * dpr)
		canvas.height = Math.round(cssH * dpr)
		canvas.style.width = `${cssW}px`
		canvas.style.height = `${cssH}px`
		ctx!.setTransform(dpr, 0, 0, dpr, 0, 0)

		grid = { cols, rows, cw, ch }
		prev = new Uint8Array(cols * rows).fill(255)
		atlas = null // force rebuild at current metrics
		atlasEdge = null
		atlasAccent = null
		cssWidth = cssW
	}

	function ensureAtlas(ramp: string) {
		if (atlas && atlasRamp === ramp) return
		atlas = buildAtlas(ramp, grid.cw, grid.ch, dpr, FIELD_MAX)
		atlasEdge = buildAtlas(ramp, grid.cw, grid.ch, dpr, FIELD_MAX_EDGE)
		atlasAccent = buildAtlas(ramp, grid.cw, grid.ch, dpr, FIELD_ACCENT)
		atlasRamp = ramp
		alpha = alphaRamp(ramp.length)
		prev.fill(255)
	}

	function draw(now: number, dt = 0) {
		const p = paramsRef.current.current
		const target = paramsRef.current.target

		// Ease toward the section preset inside the existing loop — no second
		// driver, no React render.
		p.speed += (target.speed - p.speed) * 0.05
		p.density += (target.density - p.density) * 0.05
		p.accent += (target.accent - p.accent) * 0.05
		if (p.ramp !== target.ramp) p.ramp = target.ramp

		// Ease toward the damped speed rather than snapping, so starting and
		// stopping a scroll doesn't itself read as a change in the animation.
		damp += (dampTarget - damp) * 0.08
		clock += dt * p.speed * damp

		ensureAtlas(p.ramp)
		const rampLen = p.ramp.length
		const { cols, rows, cw, ch } = grid
		const cwDev = Math.ceil(cw * dpr)
		const chDev = Math.ceil(ch * dpr)
		const t = clock
		// Only the very brightest glyph is ever eligible for the accent, and only a
		// `p.accent` fraction of those. That restraint is the whole difference
		// between "technical" and "matrix screensaver".
		const brightest = rampLen - 1
		const accent = p.accent

		for (let y = 0; y < rows; y++) {
			for (let x = 0; x < cols; x++) {
				const i = y * cols + x
				const v = field(x, y, t) * p.density + BAYER8[(y & 7) * 8 + (x & 7)] * (DITHER / rampLen)
				let g = (v * rampLen) | 0
				g = g < 0 ? 0 : g >= rampLen ? rampLen - 1 : g

				if (g === prev[i]) continue
				prev[i] = g

				const px = x * cw
				const py = y * ch
				// clearRect, not fillRect — the wrapper's static Bayer texture must
				// composite through, so the animated and static states share a base.
				ctx!.clearRect(px, py, cw, ch)
				if (g === 0) continue

				// Swapping the source atlas is the whole tinting mechanism — no
				// compositing modes, which would blend against the transparent
				// canvas rather than the glyph and leave holes as neighbouring
				// cells are cleared.
				const src =
					g === brightest && accent > 0 && hash01(x, y) < accent
						? atlasAccent!
						: isGutterCell(x, cw, cssWidth)
							? atlasEdge!
							: atlas!

				ctx!.globalAlpha = alpha[g]
				ctx!.drawImage(src, g * cwDev, 0, cwDev, chDev, px, py, cw, ch)
			}
		}
		ctx!.globalAlpha = 1
	}

	function frame(now: number) {
		raf = requestAnimationFrame(frame)
		// -1 absorbs rAF jitter; without it a 15fps gate on a 60Hz display
		// quantises down to 12fps.
		if (now - last < interval - 1) return
		// Cap dt so returning to a backgrounded tab does not jump the phase.
		const dt = last ? Math.min((now - last) / 1000, 0.25) : 0
		last = now
		draw(now, dt)
	}

	function start() {
		if (destroyed || reduced || raf) return
		last = 0
		raf = requestAnimationFrame(frame)
	}

	function stop() {
		if (raf) cancelAnimationFrame(raf)
		raf = 0
	}

	/* --- lifecycle --------------------------------------------------------- */

	layout()
	// Paint one frame immediately so the field is present without waiting for
	// the deferred loop; the static texture covers the gap either way.
	draw(0)

	const lowPower = isLowPower()

	// Two rAFs clear first paint, then idle time clears hydration. The field must
	// never compete with the work that produces LCP.
	if (!reduced && !lowPower) {
		requestAnimationFrame(() =>
			requestAnimationFrame(() => {
				if ("requestIdleCallback" in window) {
					;(window as Window & typeof globalThis).requestIdleCallback(start, { timeout: 1200 })
				} else {
					setTimeout(start, 400)
				}
			})
		)
	}

	let resizeTimer: ReturnType<typeof setTimeout> | undefined
	let lastW = wrap.clientWidth
	let lastH = wrap.clientHeight
	const ro = new ResizeObserver(() => {
		const w = wrap.clientWidth
		const h = wrap.clientHeight
		// Mobile URL-bar show/hide fires a height-only resize constantly. Rebuilding
		// the atlas mid-scroll for that would be the worst jank on the page.
		if (w === lastW && Math.abs(h - lastH) < 120) return
		lastW = w
		lastH = h
		clearTimeout(resizeTimer)
		resizeTimer = setTimeout(() => {
			if (destroyed) return
			layout()
			draw(performance.now())
		}, 150)
	})
	ro.observe(wrap)

	// The canvas is `position: fixed; inset: 0`, so an IntersectionObserver on it
	// would always report intersecting. Visibility is the only real pause signal.
	const onScroll = () => {
		dampTarget = SCROLL_DAMP
		clearTimeout(scrollTimer)
		scrollTimer = setTimeout(() => {
			dampTarget = 1
		}, SCROLL_SETTLE_MS)
	}
	window.addEventListener("scroll", onScroll, { passive: true })

	const onVisibility = () => {
		if (document.hidden) stop()
		else if (!reduced && !lowPower) start()
	}
	document.addEventListener("visibilitychange", onVisibility)

	const mq = typeof matchMedia === "function" ? matchMedia("(prefers-reduced-motion: reduce)") : null
	const onMotionChange = (e: MediaQueryListEvent) => {
		reduced = e.matches
		if (reduced) {
			stop()
			canvas.style.opacity = "0"
		} else {
			canvas.style.opacity = ""
			start()
		}
	}
	mq?.addEventListener("change", onMotionChange)
	if (reduced) canvas.style.opacity = "0"

	return {
		destroy() {
			destroyed = true
			stop()
			clearTimeout(resizeTimer)
			ro.disconnect()
			window.removeEventListener("scroll", onScroll)
			clearTimeout(scrollTimer)
			document.removeEventListener("visibilitychange", onVisibility)
			mq?.removeEventListener("change", onMotionChange)
		},
	}
}

export { PRESETS }
